### ISSUE TITLE
Email type is not proper validating emails

### ISSUE THREAD

**Issue by alguerocode** [devSupporters/volder#78]
the Email type function is not properly validate email correctly we need more improvement. and accept mutliemail styles not only the `Gmail style`

this is current Email function:
```js
export const Email = (input) => {
  const regex = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/

  return regex.test(String(input))
};
```

**Comment by batunpc** [comment]
` const Email = (input) => {
  return /[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+/.test(input);
}`
This change in the regexp might be helpful to validate/accept "mutliemail" styles.

**Comment by alguerocode** [comment]
> ` const Email = (input) => { return /[^@ \t\r\n]+@[^@ \t\r\n]+\.[^@ \t\r\n]+/.test(input); }` This change in the regexp might be helpful to validate/accept "mutliemail" styles.
the email structure `[email name]@[domain name]
the current email regex it's true, but the email name wants some changes:
- add more symbols to accept them and it's : `& + ~` 
- email don't accept the emain names that start with symbols

**Comment by batunpc** [comment]
`^[\w.+~&\-]+@[a-zA-Z\d.-]+\.[a-zA-Z]{2,6}` 

This will match in the beginning `[email name]` if there is 
\w (alphanumeric or underscore character with the stated symbols &,+,~) followed by domain name. 

I tested from here [regex101](https://regex101.com/)
I hope this helps:)

**Comment by alguerocode** [comment]
thanks and the finally the create pull request
